import { z } from 'zod';

/**
 * Zod schema validating structured preference values parsed from free text by Amazon Bedrock.
 */
export const BedrockPreferenceParseSchema = z.object({
  preferredGenres: z.array(z.string()).default([]),
  excludedGenres: z.array(z.string()).default([]),
  moods: z.array(z.string()).default([]),
  maximumRuntimeMinutes: z.number().int().positive().nullable().optional().default(null),
  maximumContentRating: z.string().nullable().optional().default(null),
  avoidContentTags: z.array(z.string()).default([]),
});

export type BedrockParsedPreferences = z.infer<typeof BedrockPreferenceParseSchema>;

/**
 * Zod schema validating consensus explanation generated by Amazon Bedrock from verified score data.
 */
export const BedrockExplanationSchema = z.object({
  explanation: z.string().min(10).max(500),
  groupHighlight: z.string().min(5).max(200),
});

export type BedrockExplanation = z.infer<typeof BedrockExplanationSchema>;

/**
 * Zod schema validating a group consensus summary generated by Amazon Bedrock.
 */
export const BedrockGroupSummarySchema = z.object({
  summary: z.string().min(10).max(400),
});

export type BedrockGroupSummary = z.infer<typeof BedrockGroupSummarySchema>;
